"""Persona-aware formatting for deterministic chat errors.

Most successful assistant replies are generated by the LLM and therefore pass
through the persona-aware system prompt.  Errors raised by infrastructure,
plan execution, websockets, or circuit breakers can bypass the LLM entirely;
this module keeps those user-visible fallbacks useful, clearly marked, and in
character.
"""

from __future__ import annotations

from src.ai.persona_context import PersonaContext
from src.ai.language import detect_user_language_label


class AgentErrorPresenter:
    """Format user-visible error messages with persona-appropriate style.

    The presenter deliberately keeps humor small and predictable.  It should
    never swallow technical information, because maintainers and users need the
    exact failure to diagnose issues.  Extend this class with new methods when
    a new subsystem needs a distinct error shape rather than formatting ad-hoc
    strings in the call site.
    """

    def __init__(self, persona_name: str = "default") -> None:
        """Create a presenter bound to the active persona settings value.

        Args:
            persona_name: The active persona name from Settings.
        """
        self._persona = PersonaContext(persona_name)

    def circuit_open(self, operation: str = "AI service") -> str:
        """Return a friendly service-unavailable error for circuit breakers.

        Args:
            operation: Human-readable subsystem or operation name.
        """
        return self.format_error(
            title="AI service temporarily unavailable",
            operation=operation,
            detail="The AI service circuit breaker is open. Please try again in a minute.",
            hint="No data was changed.",
        )

    def iteration_limit(self) -> str:
        """Return a fallback when the agent loop exhausts its iterations."""
        return self.format_error(
            title="request did not complete",
            operation="agent reasoning loop",
            detail="The assistant hit its iteration limit before reaching a final answer.",
            hint="Try the request again; the previous attempt made no verified changes beyond completed tool actions.",
        )

    def exception(self, operation: str, exc: BaseException | str) -> str:
        """Return a useful error for unexpected exceptions.

        Args:
            operation: Context for where the exception occurred.
            exc: The exception object or already formatted detail.
        """
        return self.format_error(
            title="unexpected error",
            operation=operation,
            detail=str(exc) or type(exc).__name__,
        )

    def plan_failure(self, tool_name: str, detail: str) -> str:
        """Return an error for a failed deterministic plan step.

        Args:
            tool_name: The tool or step that failed.
            detail: Exact failure detail returned by the tool or executor.
        """
        return self.format_error(
            title="planned step failed",
            operation=f"planned step `{tool_name}`",
            detail=detail,
        )

    def queue_failure(self, detail: str, user_prompt: str | None = None) -> str:
        """Return a language-aware error for an unverified queue operation."""
        if detect_user_language_label(str(user_prompt or "")) == "Italian":
            safe_detail = detail.strip() if detail else "Errore sconosciuto"
            return "\n".join([
                "⚠️ **Download non messo in coda**",
                "Il downloader non ha confermato un nuovo download attivo.",
                f"**Dettagli:** `{safe_detail}`",
                "Non lo segnalo come attivo finché il downloader non restituisce una ricevuta verificata.",
            ])
        return self.format_error(
            title="download was not queued",
            operation="queue download",
            detail=detail,
            hint="No download is reported as active unless the downloader returned a verified queue receipt.",
        )

    def queue_partial_failure(self, success_count: int, detail: str, user_prompt: str | None = None) -> str:
        """Return a truthful receipt when only part of a queue request succeeded."""
        count = max(0, int(success_count or 0))
        safe_detail = detail.strip() if detail else "Unknown queue error"
        if detect_user_language_label(str(user_prompt or "")) == "Italian":
            noun = "download" if count == 1 else "download"
            return "\n".join([
                "⚠️ **Coda completata solo in parte**",
                f"Il downloader ha confermato {count} {noun}, ma almeno un altro elemento non è stato messo in coda.",
                "**Operazione:** coda download",
                f"**Dettagli del fallimento:** `{safe_detail}`",
                "Considero attivi solo gli elementi con una ricevuta verificata dal downloader.",
            ])
        noun = "download" if count == 1 else "downloads"
        return "\n".join([
            "⚠️ **The queue request completed only in part**",
            f"The downloader verified {count} {noun}, but at least one other item was not queued.",
            "**Operation:** queue download",
            f"**Failure details:** `{safe_detail}`",
            "Only items with a verified downloader receipt are being reported as active.",
        ])

    def batch_queue_failure(self, detail: str) -> str:
        """Return an error for automatic batch queueing failures.

        Args:
            detail: Exact batch queue failure detail.
        """
        return self.format_error(
            title="batch download was not fully queued",
            operation="recommended batch queue",
            detail=detail,
        )

    def format_error(
        self,
        title: str,
        operation: str,
        detail: str,
        hint: str | None = None,
    ) -> str:
        """Build the final markdown error message shown to the user.

        Args:
            title: Short human-readable title after the Error marker.
            operation: Operation or subsystem that failed.
            detail: Actionable technical detail; keep exact error text here.
            hint: Optional recovery advice.

        Returns:
            Markdown formatted error text with a clear error marker.
        """
        safe_detail = detail.strip() if detail else "Unknown error"
        lines = [
            f"⚠️ **Error — {title}**",
            f"**Operation:** {operation}",
            f"**Details:** `{safe_detail}`",
        ]
        if hint:
            lines.append(f"**Next step:** {hint}")
        return "\n".join(lines)
